### ISSUE TITLE
Hello, can this problem be fixed? Try to show that the repair failed many times. Is it thunderbolt brick?

### ISSUE THREAD

**Issue by a13302211596** [osy86/ThunderboltPatcher#1]
HaC-Mini-2.3.3
How do you do? Can you help me with the repair, thank you
<img width="247" alt="C9E67C95-D8F5-4C85-B9A2-49B2E9D0A957" src="https://user-images.githubusercontent.com/53515825/68058184-4b4ce200-fd33-11e9-8c25-93bc792122f2.png">

<img width="1280" alt="截屏2019-11-02上午5 26 45" src="https://user-images.githubusercontent.com/53515825/68057875-450a3600-fd32-11e9-9e63-efce7f6a845d.png">
<img width="515" alt="372A1B55-5E1C-48A4-9233-2208C8824736" src="https://user-images.githubusercontent.com/53515825/68058018-c5309b80-fd32-11e9-89ac-433789a422ae.png">
![Uploading BADA68FA-502F-464A-8C0B-654FFAA818A5.png…]()

**Comment by osy** [comment]
You need to patch AppleHPMDevice@70. it should be selected automatically when you launch the patcher.

**Comment by a13302211596** [comment]
> You need to patch AppleHPMDevice@70. it should be selected automatically when you launch the patcher.
applehpmdevice @ 70, indicating that the repair failed

**Comment by a13302211596** [comment]
@osy86 70，76，4E，Repair failure

**Comment by a13302211596** [comment]
@osy86 HaC-Mini-2.2 Fixed successfully. Thunderbolt disappeared after upgrading HaC-Mini 2.3.3. Go back to HaC-Mini 2.2, still can't find thunderbolt

**Comment by osy** [comment]
Tool not compatible with 2.2. You must upgrade to 2.3 first then use the tool. Select @70 and get a dump using File -> Dump.

**Comment by a13302211596** [comment]
> Tool not compatible with 2.2. You must upgrade to 2.3 first then use the tool. Select @70 and get a dump using File -> Dump.

Can it be repaired now

**Comment by a13302211596** [comment]
@osy86 Can it be repaired now

**Comment by a13302211596** [comment]
<img width="518" alt="729BD033AC18E1293402380E539A8798" src="https://user-images.githubusercontent.com/53515825/68061119-4c374100-fd3e-11e9-89d2-dce32f8dee42.png">

**Comment by a13302211596** [comment]
<img width="518" alt="729BD033AC18E1293402380E539A8798" src="https://user-images.githubusercontent.com/53515825/68061207-ad5f1480-fd3e-11e9-89a2-e7322074363d.png">

**Comment by a13302211596** [comment]
@osy86 File -> Dump
[Untitled.zip](https://github.com/osy86/ThunderboltPatcher/files/3799881/Untitled.zip)

**Comment by a13302211596** [comment]
> @osy86 File -> Dump
> [Untitled.zip](https://github.com/osy86/ThunderboltPatcher/files/3799881/Untitled.zip)

windows No thunderbolt display

**Comment by osy** [comment]
Please make sure you are dumping AppleHPMDevice@70. I see the wrong SPI.

**Comment by lmshsqlc** [comment]
After some direct messages, the device has been returned the device to Intel after some improper bios external flashing. This issue should be closed.

**Comment by osy** [comment]
I see
