### ISSUE TITLE
Thunderbolt Patcher failed

### ISSUE THREAD

**Issue by TheBigJam** [osy86/ThunderboltPatcher#2]
Describe the bug:
-Writing process aborted
-Unable to uninstall the patch

Expected behavior:
Normal flash procedure

**Configuration**
- HaC Mini version: 3.3
- OSX version: 10.15.1
- NUC model: NUC8i7HVK
- Boot SSD model and protocol: XPG Gammix S11 480GB, NVMe
- Second SSD model and protocol 
- First DIMM model: GSkill DDR4-2666 8GB
- Seconnd DIMM model: GSkill DDR4-2666 8GB
- Display port(s) used: 2
- Display resolution(s): Standard HD
- Wifi: BCM94360CS2
- Any TB3 devices: 
- Any USB devices: 

Patching failed:
![20191104_222503](https://user-images.githubusercontent.com/55004532/68161036-4a939600-ff55-11e9-90ec-72acd8887722.jpg)

Uninstall failed as well:
![20191104_223249](https://user-images.githubusercontent.com/55004532/68161038-4b2c2c80-ff55-11e9-941d-e1eb33a8d825.jpg)

How can i fash the original Firmware again?

**Comment by osy** [comment]
Can you go to File->Dump and post your dump?

To recover from a bad flash you must boot into windows with a device plugged in and use Intel’s thunderbolt updater.

**Comment by TheBigJam** [comment]
Here comes the dump:

EDIT: It comes from @76

[DUMP.zip](https://github.com/osy86/ThunderboltPatcher/files/3806447/DUMP.zip)

**Comment by TheBigJam** [comment]
The dump above was from @76. This was the automatic selection. The attached dump is from @70.
The windows flas tool first made an registry entry. Afterrebooting the flash utility does not start.
What can i do now?

[DUMP@70.zip](https://github.com/osy86/ThunderboltPatcher/files/3806501/DUMP%4070.zip)

**Comment by osy** [comment]
Actually the Windows tool is pretty bad. You need to install intel’s older drivers for it to work. If you can’t get it to work, you can also try from Linux using the same file image from the windows build. Or if you can wait, I’ll look into the issue this weekend.

**Comment by TheBigJam** [comment]
I have a Linux live pendrive. Can i install the firmware from there? What are the steps and which programs do i need additionally? I had no luck in Windows, trying 4 oder drivers...

**Comment by osy** [comment]
Follow this https://wiki.archlinux.org/index.php/Dell_XPS_13_(9360)#Thunderbolt_Firmware_updates but use the firmware bin from intel.

**Comment by osy** [comment]
Once you recover, can you get another dump before flashing?

**Comment by TheBigJam** [comment]
> Once you recover, can you get another dump before flashing?

Yes, but i had no luck so far. 
Now i bought such a "CH341" flasher and will flash the original firmware directly to the chip. I hope it will work.

**Comment by osy** [comment]
Linux instructions didn’t work?

**Comment by TheBigJam** [comment]
> Linux instructions didn’t work?

No not really. I was unable to power on the controller. And there is no thunderbolt recognized in /sys/bus/

**Comment by osy** [comment]
I noticed in the dump that many of the read commands failed silently. And I surmise that some write commands failed also. I can’t reproduce it on my system though so it’s weird.

When in Linux, do you have a TB or USB device plugged in?

**Comment by TheBigJam** [comment]
I also can't imagine what goes wrong. But this flasher things are cheap and nice to have for future.

Yes i tried it with Thunderbolt and USB.

**Comment by osy** [comment]
I see Linux doesn’t recognize it because your config section is corrupted. We need more people to dump their flash (but NOT patch). I need to see if this is just an issue with command response or if wrong commands are being sent.

**Comment by osy** [comment]
If we know that write command isn’t broken, I can build a custom patch file that can fix it.

**Comment by TheBigJam** [comment]
Once I got it repaired, I will continue to support.

**Comment by lmshsqlc** [comment]
This is a dump file from my NUC8I7HNK.  This was dumped before any patch. 
This dump was created on 31 Oct 2019. 
Host Device: NUC8I7HNK
Device: TPS65982 HW0011 FW0001.12.06 ZTBT1
Firmware version from intel: v33 latest
ACPI Path: /AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/I2C2@15,2/AppleIntelLpssI2C@2/AppleIntelLpssI2CController@2/HPM1@0/AppleHPMLPSS/AppleHPMDevice@70


[Thunderbolt Firmware Dump.zip](https://github.com/osy86/ThunderboltPatcher/files/3812325/Thunderbolt.Firmware.Dump.zip)

**Comment by osy** [comment]
@lmshsqlc you've updated to v33 from intel before patching, correct?

**Comment by lmshsqlc** [comment]
> @lmshsqlc you've updated to v33 from intel before patching, correct?

It should be v33 from Intel before patching. This dump comes before patching.

**Comment by TheBigJam** [comment]
Hello,

before i start to flash the chip with an external falsher, I have a question:

When i compare the firmware file from intel with the dump, i noticed that there is mutch more data in the dump than in the original firmware. The dump contains data until 0xC8FF0, the binary from intel contains only data until 0x4AFF0. 
Does this mean, I schould only overwrite the intel firmware to the chip without erasing it before?

**Comment by osy** [comment]
No, your dump has a different active partition.

**Comment by TheBigJam** [comment]
> No, your dump has a different active partition.

So I can erase the chip and then simply copy Intel's .bin file to it?

**Comment by osy** [comment]
Since your dump was corrupted I think your best bet is to flash the backup from @lmshsqlc

**Comment by TheBigJam** [comment]
I also thought about that... I will tell the results tomorrow.

**Comment by TheBigJam** [comment]
So here come my results:

I used a "CH341A" USB falsh tool and the "AsProgrammer" to write the data to the chip:
![20191107_143635](https://user-images.githubusercontent.com/55004532/68411424-c165a480-018a-11ea-8cc3-04bf6d9f556c.jpg)


First I copied the backup.bin from Imshsqlc to the chip with semi success. The Thunderbolt Patcher still wasn't finding a matching firmware. However i was able to run the Intel Thunderbolt update utility in windows - it was broken before.
After that I tried the Thunderbolt pathcher in MacOS again. The firmware was now recogniced and I was able to run the patch sequence. But unfortunately it crashed again. I tried this procedure many times, and the patch  always sequence crashed at different addresses:

First try:
![20191107_132252](https://user-images.githubusercontent.com/55004532/68411061-148b2780-018a-11ea-9970-e36d6e6e3ca7.jpg)

Second try
![20191107_140101](https://user-images.githubusercontent.com/55004532/68411100-253b9d80-018a-11ea-831c-1c99c107adf8.jpg)

...

After that I erased the chip again and wrote the binary provided from intel to it. This time the patch procedure went trough successfully!

Note:
My Thunderbolt Patcher alwys selects the device "@4E" automatically and i have to put it to "@70" manually every time. I'm also unable to "Uninstall" the patch. It crashes every time with a random writing error. To unpatch i need to use the "CH341" tool and the original firmware. But for the moment it is working:
![20191107_182137](https://user-images.githubusercontent.com/55004532/68412400-70ef4680-018c-11ea-987b-22e536f96411.jpg)


Tomorrow i will be intense testing TB functionality (Hotplug etc.)

Attached files:
DUMP_Restored contains the working fw without TB patch
DUMP_Patched contains the patched firmware

**Comment by osy** [comment]
I’m not able to see your attachments.

**Comment by TheBigJam** [comment]
> I’m not able to see your attachments.

Sorry....
[DUMP_Restored.zip](https://github.com/osy86/ThunderboltPatcher/files/3820965/DUMP_Restored.zip)
[Dump_Patched.zip](https://github.com/osy86/ThunderboltPatcher/files/3820966/Dump_Patched.zip)

**Comment by osy** [comment]
Okay weird. I still see the read corruption issue. I can’t think of any reason why though, I wasn’t able to reproduce on my machine. There doesn’t seem to be anything weird with your config either.

**Comment by TheBigJam** [comment]
It is an absolutely clean installation of V 2.3.3. The only thing I changed in the config was the ID's (UUID, Serial and MLB)

**Comment by osy** [comment]
[tbpatch.zip](https://github.com/osy86/ThunderboltPatcher/files/3821030/tbpatch.zip)

Can you try this modified tool. Start with a clean SPI (flash backup externally). Then do `sudo tbpatch patch -p AppleHPMDevice@70 -f path/to/patch.plist` and after it's complete. Run `sudo tbpatch dump -p AppleHPMDevice@70 -o 0x82000 -s 0x1000 -f path/to/dumpX.bin` ten times and zip up all 10 dumps and attach it here.

**Comment by TheBigJam** [comment]
> dump -p AppleHPMDevice@70 -o 0x82000 -s 0x1000 -f

Here it comes:
[Dumps.zip](https://github.com/osy86/ThunderboltPatcher/files/3821190/Dumps.zip)

**Comment by TheBigJam** [comment]
> > dump -p AppleHPMDevice@70 -o 0x82000 -s 0x1000 -f
> 
> Here it comes:
> [Dumps.zip](https://github.com/osy86/ThunderboltPatcher/files/3821190/Dumps.zip)

I hope i did it right:
1. Erase
2. Flash original firmware 
3. Patch 
4. Dump 10 times

Ok ?

**Comment by osy** [comment]
Did this come after a restore? I don’t see an active partition in 0x82000 as your previous screenshot indicates. If when patching you saw messages about 0x4000 then instead dump that region (for size 0x1000).

I did see a read corruption in dump10. So it appears not to be an issue with the driver/tool but with TI’s chip.

**Comment by TheBigJam** [comment]
Yes i restored it first.
After "successful" patch run through there was no thunderbolt support
Now i flashed back the backup and everything is fine.

Thats rally weird!

**Comment by osy** [comment]
[tbpatch-2.zip](https://github.com/osy86/ThunderboltPatcher/files/3821241/tbpatch-2.zip)
I added a sleep before saving the data from the read command. Can you do the dump test again (no need for flashing or anything). This time, do it 50 times (you may want to write a shell script). But you don't have to share the dump, just get a SHA hash on every one and tell me how many had different hashes. Then post the ones with different hashes. thanks

**Comment by TheBigJam** [comment]
By the way...
Should i give you a tutorial for my wifi hack?
I can use both SSD slots - this might be interesting for the Hac mini.

**Comment by osy** [comment]
Sure post it in an issue in the other repo.

**Comment by TheBigJam** [comment]
> [tbpatch-2.zip](https://github.com/osy86/ThunderboltPatcher/files/3821241/tbpatch-2.zip)
> I added a sleep before saving the data from the read command. Can you do the dump test again (no need for flashing or anything). This time, do it 50 times (you may want to write a shell script). But you don't have to share the dump, just get a SHA hash on every one and tell me how many had different hashes. Then post the ones with different hashes. thanks

oouh thats too high for me....

I dont know how to do this.

**Comment by osy** [comment]
`openssl dgst -sha256 path/to/file` anyways if it’s easier just attach all the files.

**Comment by TheBigJam** [comment]
how can i create such a shell script? i might can do this in windows batch - but in macos i have no idea. I'm really new in macos / hackintosh / linux.

**Comment by osy** [comment]
It’s fine then just do what you did before and generate 10 files and we can move on from there.

**Comment by TheBigJam** [comment]
Here come 12 dumps
[Dumps 2.zip](https://github.com/osy86/ThunderboltPatcher/files/3821301/Dumps.2.zip)

**Comment by TheBigJam** [comment]
> Sure post it in an issue in the other repo.

I will do that this weekend

**Comment by osy** [comment]
[check.sh.zip](https://github.com/osy86/ThunderboltPatcher/files/3821340/check.sh.zip)
Run `sudo ./check.sh` make sure tbpatcher is in the same directory. This will keep dumping until it finds a corruption. Run it until it terminates and attach dump.bin. If it doesn't terminate in a long time (like say an hour), then we're good and you can kill it.

**Comment by TheBigJam** [comment]
It doesn't work:

iMac:~ jan$ /Users/jan/Desktop/Check/check.sh 
/Users/jan/Desktop/Check/check.sh: line 7: ./tbpatch: No such file or directory
shasum: dump.bin: 
0: 

Both files are in the directory

**Comment by osy** [comment]
tbpatch is in the same directory?

**Comment by TheBigJam** [comment]
> It doesn't work:
> 
> iMac:~ jan$ /Users/jan/Desktop/Check/check.sh
> /Users/jan/Desktop/Check/check.sh: line 7: ./tbpatch: No such file or directory
> shasum: dump.bin:
> 0:
> 
> Both files are in the directory

now it works. i forgot the ./

**Comment by TheBigJam** [comment]
It ended after 31 cycles:

Reading 0x00082FF0
31: fce524dc5c5eaca8ccf851d18801d8070d078cf7
[dump.bin.zip](https://github.com/osy86/ThunderboltPatcher/files/3821436/dump.bin.zip)

**Comment by osy** [comment]
[tbpatch-3.zip](https://github.com/osy86/ThunderboltPatcher/files/3821446/tbpatch-3.zip)
Replace tbpatch with this and try again. I bumped the wait time up higher.

**Comment by TheBigJam** [comment]
I noticed something else:
Since I have the fw patched, the computer stucks sometimes with black screen (before intel nuc logo comes). It only seem to happen when i reboot.

**Comment by osy** [comment]
Yeah, that happens sometimes due to the controller not following the proper shutdown sequence.

**Comment by TheBigJam** [comment]
Crash after 5 cycles. 
It must have another reason.

**Comment by osy** [comment]
[tbpatch-4.zip](https://github.com/osy86/ThunderboltPatcher/files/3821715/tbpatch-4.zip)

Please try this one.

**Comment by osy** [comment]
[TBPatch.zip](https://github.com/osy86/ThunderboltPatcher/files/3822178/TBPatch.zip)
If that works, here's an updated GUI tool. Replace it in Thunderbolt Patcher.app/Applications/TBPatcher.app. It will attempt to flash 100 times, each time if it reads back the flashed data is incorrect, it will try again.

**Comment by TheBigJam** [comment]
> 
> 
> [tbpatch-4.zip](https://github.com/osy86/ThunderboltPatcher/files/3821715/tbpatch-4.zip)
> 
> Please try this one.

1736 cycles with no errors! - You got it, man! :-)

**Comment by osy** [comment]
Great! Please replace the GUI app with the one above and re-try the flashing. If it works, it'll make sure nobody bricks again.

**Comment by TheBigJam** [comment]
It seems tow work fine!
Thunderbolt works great. Just tested it with an Lenovo TB3 dock. Hotplug is no problem.
Great job! - Thanks!
