### ISSUE TITLE
Can't update TB firmware. 

### ISSUE THREAD

**Issue by Deftaudio** [osy86/ThunderboltPatcher#4]
Hello, please, suggest I'm following your guide to update TB FW on Hades Canyon, that I setup over a year ago for OSX.
I'd like to use it in Native TB3 mode, and initially attempted to update with the GUI, which failed and then I moved to the command line. I also made a backup of my existing firmware. Would you please help me to understand why the update process is failed(per screenshot)? Did I actually succeed updating it on the first attempt? Sorry if I'm asking simple questions, just want to make sure it everything properly. 
![Screen Shot 2020-07-23 at 8 20 05 PM](https://user-images.githubusercontent.com/3469541/88357997-2a457a80-cd22-11ea-8d71-55d462e2beec.png)
![Screen Shot 2020-07-23 at 12 35 51 PM](https://user-images.githubusercontent.com/3469541/88358008-30d3f200-cd22-11ea-84f2-5ed92f11c30e.png)
![Screen Shot 2020-07-23 at 12 36 22 PM](https://user-images.githubusercontent.com/3469541/88358020-3af5f080-cd22-11ea-9e3f-092b191ca422.png)

[backup.bin.zip](https://github.com/osy86/ThunderboltPatcher/files/4970073/backup.bin.zip)

**Comment by osy** [comment]
This tool does not do any firmware upgrades. If you run it twice it will always fail because you’ve already patched.

**Comment by Deftaudio** [comment]
Thank you, based on the dump file can you please tell me if it's patched properly?

**Comment by osy** [comment]
There’s no way for me to tell. I don’t have the patches memorized. If it succeeded at least once it works.
