### ISSUE TITLE
Information about ThunderboltPatcher

### ISSUE THREAD

**Issue by Purpleman666** [osy86/ThunderboltPatcher#7]
Hello, 

I just have a question : 
I have a nuc 8i7HVK and I want to patch the thunderbolt chipset. 
But when i look at my device list, i just found 1x I2C2 devices and one I2C1 devices. Is it normal ???, because on your tutoriel, there's RP05 and don't see it in my list. 
Can you just tell me if it's possible to patch it. I attache a dump of my chip and my list. 
Thank you for your answer.

/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/I2C2@15,2/AppleIntelLpssI2C@2/AppleIntelLpssI2CController@2/HPM1@0/AppleHPMLPSS/AppleHPMDevice@4E
  Address : 0x0000004E
  PID     : 0x2831454341
  UID     : 1DAD3810-63CA-108C-5F40-9D7549BB9A4D
  Version : 
  Build   : 708ef7fef06b3a126fd0e433f097fed7975c3730_09112017
  Device  : TPS65982 HW0011 FW0001.12.06 ZTBT1

/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/I2C1@15,1/AppleIntelLpssI2C@1/AppleIntelLpssI2CController@1/HPM0@0/AppleHPMLPSS/AppleHPMDevice@76
  Address : 0x00000076
  PID     : 0x2831454341
  UID     : 41AD3810-872C-2BBC-4440-DA27EE4DE246
  Version : 
  Build   : 708ef7fef06b3a126fd0e433f097fed7975c3730_09112017
  Device  : TPS65982 HW0011 FW0001.12.06 ZTBT1

/AppleACPIPlatformExpert/PCI0@0/AppleACPIPCI/I2C2@15,2/AppleIntelLpssI2C@2/AppleIntelLpssI2CController@2/HPM1@0/AppleHPMLPSS/AppleHPMDevice@70
  Address : 0x00000070
  PID     : 0x2831454341
  UID     : 63AD3810-2ADA-CEA4-5443-9E41E3C3CF21
  Version : 
  Build   : 708ef7fef06b3a126fd0e433f097fed7975c3730_09112017
  Device  : TPS65982 HW0011 FW0001.12.06 ZTBT1

[backup.bin.zip](https://github.com/osy/ThunderboltPatcher/files/6052350/backup.bin.zip)

**Comment by osy** [comment]
The one with address `0x00000070` is probably the right one. You're not seeing RP05 because you probably didn't install the right drivers/ACPI to get it working (or your controller is bricked). If you're using HaC Mini, install Legacy Thunderbolt to see it. Otherwise, I think there's guides/samples in this repo to help.

**Comment by Purpleman666** [comment]
Thank you for your answer.

**Comment by Purpleman666** [comment]
Sorry but i got another question. 
I test my thunderbolt ports under windows, and no probleme, they are working well and i didn't try to patch them for now. So for me they arr not bricked. I them in ioreg, and when i plug a thunderbolt device, i see them in ioreg but not in osx. 
I looked at my EFI and i've got the SSDT-TbtLegacy.aml and SSDT-Xhci.aml and it is active in the config.plist. 
I've check in the bios, i'm well in legacy option for thunderbolt. 
If you can just show me the way, because at this point, i don't understand why it's not working. 

<img width="1920" alt="Capture d’écran 2021-03-01 à 16 56 40" src="https://user-images.githubusercontent.com/59150995/109524511-e6cd9e80-7ab0-11eb-87e0-bf9c35d10f76.png">

<img width="1920" alt="Capture d’écran 2021-03-01 à 17 03 20" src="https://user-images.githubusercontent.com/59150995/109524487-e1705400-7ab0-11eb-9c2f-b854f7fbb054.png">


Thank you for your answer. 
Have a good day.

**Comment by osy** [comment]
> You're not seeing RP05 because you probably didn't install the right drivers/ACPI to get it working ... If you're using HaC Mini, install Legacy Thunderbolt to see it.

Did you? It doesn’t matter what you see in ioreg.
